### ISSUE TITLE
is there a way to get the polarity of scan out of mzMl file for spectrum ? 

### ISSUE THREAD

**Issue by amnahsiddiqa** [OpenMS/pyopenms-extra#103]
Hi I am new to pyopenms
I needed to extract the scan polarity ; I think I can use the tag 'MS:1000130' in mzml file; but I am unable to understand how I can use getitem to do that;  so far I understood that I could do that with it ; 

`        <cvParam cvRef="MS" accession="MS:1000130" value="" name="positive scan" />
                `
Any example code  will be appreciated. 
Thanks
Amnah

**Comment by oliveralka** [comment]
Hi, 
in the most mzML files I had a look the CVTerm "MS:1000130" is added at spectrum level. This allows to check the polarity. 

Here a short example:
```
from pyopenms import *
from urllib.request import urlretrieve
# from urllib import urlretrieve  # use this code for Python 2.x
urlretrieve ("http://proteowizard.sourceforge.net/example_data/tiny.pwiz.1.1.mzML", "test.mzML")

exp = MSExperiment()
MzMLFile().load("test.mzML", exp)

// here only the first spectrum in the file is used to check the polarity
polarity = exp.getSpectrum(0).getInstrumentSettings().getPolarity()

if (polarity == IonSource.Polarity.POLNULL):
    print("not available")
elif (polarity == IonSource.Polarity.POSITIVE):
    print("positive")
elif (polarity == IonSource.Polarity.NEGATIVE):
    print("negative")
```

The same works analogous for MzXML files. 
```
from pyopenms import *
from urllib.request import urlretrieve
# from urllib import urlretrieve  # use this code for Python 2.x
gh = "https://raw.githubusercontent.com/OpenMS/OpenMS/develop/"
urlretrieve (gh + "src/tests/topp/FileConverter_4_input.mzXML", "test.mzXML")

exp = MSExperiment()
MzXMLFile().load("test.mzXML", exp)

polarity = exp.getSpectrum(0).getInstrumentSettings().getPolarity()

if (polarity == IonSource.Polarity.POLNULL):
    print("not available")
elif (polarity == IonSource.Polarity.POSITIVE):
    print("positive")
elif (polarity == IonSource.Polarity.NEGATIVE):
    print("negative")
```

Unfortunately, the scan polarity does not seem to be reported in .MGF files. 

If you want to split spectra based on the scan polarity, you can use something like this:
```
positive_scans = [s for s in exp.getSpectra() if s.getInstrumentSettings().getPolarity() == IonSource.Polarity.POSITIVE]
```

**Comment by roman-bushuiev** [comment]
Thank you @oliveralka, it's exactly what I was looking for!

**Comment by oliveralka** [comment]
No worries - I will close the issue, please re-open if you have further questions or comments.
