### ISSUE TITLE
pyopenms.Constants not working

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-extra#108]

**Comment by timosachsenberg** [comment]
on current whell in my installation

**Comment by oliveralka** [comment]
Which .whl are you using? 

Could you please check:
https://github.com/OpenMS/OpenMS/pull/5498/checks?check_run_id=3606959873

From #5498

**Comment by timosachsenberg** [comment]
We might need to find a way to add them automatically. Should be possible I think
