### ISSUE TITLE
IMPORTANT master+ipynb should be under the OpenMS repo

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/pyopenms-extra#151]
@rahul799 please change as soon as possible

**Comment by rahul799** [comment]
No, I just have the access to pyopenms-extra repo.

**Comment by rahul799** [comment]
@jpfeuffer please have a look #152

**Comment by rahul799** [comment]
That issue is fixed. But the test workflow still didn't work for this [commit](https://github.com/OpenMS/pyopenms-extra/commit/c362d27ec08513b5f84385caf3701476b2c3695f).
