### ISSUE TITLE
add example how protein ids are linked to peptide ids based on the getIdentifier() function

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-extra#235]

**Comment by rahul799** [comment]
When I am printing 
```
print(peptide_id.getIdentifier())
print(protein_id.getIdentifier())
```
am getting same output **IdentificationRun1** in both the cases. Is this the link you are talking about?

**Comment by timosachsenberg** [comment]
Hi Rahul.

Exactly. But we need to document somewhere more prominent that this is needed to link peptides to proteins. Otherwise, if this link is not establised some algorithms fail.

**Comment by rahul799** [comment]
Should I add it somewhere here https://pyopenms.readthedocs.io/en/latest/datastructures_id.html ? Maybe as a note?

**Comment by timosachsenberg** [comment]
that would be great. maybe in the very beginning before https://pyopenms.readthedocs.io/en/latest/datastructures_id.html#proteinidentification

**Comment by rahul799** [comment]
Ok. I will raise a PR soon.
