### ISSUE TITLE
ConsensusMap.get_metadata_df and get_intensity_df don't exist

### ISSUE THREAD

**Issue by qingyao** [OpenMS/pyopenms-extra#258]
The installed version should be latest:
pyopenms==2.7.0
pyopenms-nightly==2.6.0.dev20201009

**Comment by jpfeuffer** [comment]
Where did you get the nightly from? This is not the latest.

**Comment by qingyao** [comment]
I used pip install.
I compared just now with the Binder: 
```
? consensus_map
Type:            ConsensusMapDF
String form:     <pyopenms.dataframes.ConsensusMapDF object at 0x7f3233342dc0>
File:            /srv/conda/envs/notebook/lib/python3.7/site-packages/pyopenms/dataframes.py
Docstring:       <no docstring>
```

And for me:
```
Type:           ConsensusMap
String form:    <pyopenms.pyopenms_4.ConsensusMap object at 0x7fe4bbd86910>
File:           /mnt/mnemo6/qingyao/anaconda3/envs/new_MS_pipeline_py38/lib/python3.8/site-packages/pyopenms/pyopenms_4.cpython-38-x86_64-linux-gnu.so
Docstring:     
Cython implementation of _ConsensusMap
```

It seems the class "ConsensusMapDF" does not exist in the installed package? There is no `dataframes.py` in the pyopenms package.

**Comment by jpfeuffer** [comment]
The nightlies cannot be obtained from pip.
Either use our wheels from GitHub Actions or use conda with the openms channel.

**Comment by qingyao** [comment]
I just downloaded the wheel from https://github.com/OpenMS/OpenMS/actions/runs/1728028373
It didn't install nightly but only pyopenms==2.7.0 and still the functions do not exist. 
Now the functions are there. Thank you!
PS: conda install didn't work because of conflict, but I hadn't used openms channel, but bioconda as suggested on the Conda site: https://anaconda.org/bioconda/pyopenms
