### ISSUE TITLE
Misleading docs about TIC

### ISSUE THREAD

**Issue by fkromer** [OpenMS/pyopenms-extra#34]
In the [pyopenms docs](https://pyopenms.readthedocs.io/en/latest/getting_started.html#tic-calculation) there is an example about how to calculate the TIC from a MSExperiment. Isn't it better to use the TIC information in a [Chromatogram](https://pyopenms.readthedocs.io/en/latest/datastructures.html#chromatogram):

    tic = exp.getChromatograms()[0]
    for rt, i in zip(*tic.get_peaks()):
        # use rt and i to construct the data structure of your choice

**Comment by timosachsenberg** [comment]
Yes, I think using the TIC calculated by the instrument software is preferred over calculating it yourself.
It's just an example of how you could programmatically get a similar result.
For example, you can easily adapt the code and calculate the ion current for MS2 spectra.

**Comment by fkromer** [comment]
>  For example, you can easily adapt the code and calculate the ion current for MS2 spectra.

Good point.

**Comment by hroest** [comment]
>  For example, you can easily adapt the code and calculate the ion current for MS2 spectra.

yes, or you could calculate for a specific mass range etc. But its a good point and we could add it to the documentation
