### ISSUE TITLE
on disc reading of spectra data

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/pyopenms-extra#58]
Currently, the Spectrum viewer widget loads the whole experiment into memory.
That way it is not feasible to inspect many different mzML files.
OpenMS provides an OnDiscExperiment that doesn't load the whole mzML file into memory but directly accesses
the spectra through an index in the mzML file.
It would be beneficial to change that.

**Comment by JangJang3** [comment]
Okay, I'll work on it.
