### ISSUE TITLE
Spectral Viewer: efficient access to raw data

### ISSUE THREAD

**Issue by hroest** [OpenMS/pyopenms-extra#6]
@timosachsenberg @JeeH-K please change this to access data more efficiently using `get_peaks`, the current approach below is very inefficient:

https://github.com/OpenMS/pyopenms-extra/blob/57d9c2675d958f536c92671470d9165abde42068/src/specViewer/SpecViewer.py#L110-L116

**Comment by JeeH-K** [comment]
Thank you for the comment! Change has been made on latest commit.
